# Generated by Django 3.1.5 on 2023-05-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
