# Generated by Django 3.1.5 on 2023-05-18 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_service_products_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='products_used',
        ),
        migrations.CreateModel(
            name='ServicePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotion/')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.service')),
            ],
        ),
    ]
